dist: trusty
sudo: required
before_install:
# install general dependencies
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libicu-dev
  - sudo apt-get install -y libz-dev
  - sudo apt-get install -y pkg-config
  - sudo apt-get install -y graphicsmagick
  - sudo apt-get install -y webp
  - sudo apt-get install -y nasm
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -q
  - sudo apt-get install -y ffmpeg
  - sudo apt-get install -y gstreamer0.10-ffmpeg
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install
addons:
  apt:
    update: true
script: npm test
